export const SET_PAGE = "SET_PAGE";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_SINGLE_EVENT = "FETCH_SINGLE_EVENT";
export const FETCH_BLOG_POSTS = "FETCH_EVENTS";
export const FETCH_SINGLE_BLOG_POST = "FETCH_SINGLE_EVENT";
export const FETCH_CREW_MEMBERS = "FETCH_CREW_MEMBERS";
export const FETCH_SINGLE_CREW_MEMBER = "FETCH_SINGLE_CREW_MEMBER";
export const FETCH_CAMP_APPLICATIONS = "FETCH_CAMP_APPLICATIONS";
export const ADD_APPLICATION_COMMENT = "ADD_APPLICATION_COMMENT";
export const FETCH_APPLICATIONS_COMMENTS = "FETCH_APPLICATIONS_COMMENTS";
export const ADD_APPLICATION_REPLY = "ADD_APPLICATION_REPLY";
export const FETCH_APPLICATIONS_REPLIES = "FETCH_APPLICATIONS_REPLIES";

